blank_issues_enabled: false
contact_links:
  - name: CYBER SOLDIER on YouTube
    url: https://www.youtube.com/c/ClutterTech
    about: Watch the creator's videos
  - name: CYBER DIMENSION (Discord)
    url: https://discord.gg/6WqFnuFyfF
    about: Contact the creator and join his community
